AWK                                   = @AWK@
CAT                                   = @CAT@
CUT                                   = @CUT@
CP                                    = @CP@
RM                                    = @RM@
COMM                                  = @COMM@
CPANM                                 = @CPANM@
FIND                                  = @FIND@
GREP                                  = @GREP@
JQ                                    = @JQ@
MAKE_CPAN_DIST                        = @MAKE_CPAN_DIST@
MD5SUM                                = @MD5SUM@
MKDIR                                 = @MKDIR@
MKTEMP                                = @MKTEMP@
SORT                                  = @SORT@
UNZIP                                 = @UNZIP@
ZIP                                   = @ZIP@

